### ISSUE TITLE
編成キャプチャでエラーが発生してキャプチャできない

### ISSUE THREAD

**Issue by akiomik** [otiai10/kanColleWidget#562]
艦これウィジェットを立ち上げた状態で編成キャプチャ画面を開いてキャプチャを実行すると、以下のエラーが出てキャプチャできません。
艦これウィジェットのバージョンはv1.6.6、Chromeのバージョンは45.0.2454.85 (64-bit)で、OSはOSX 10.10.5（14F27）です。

```
Unchecked runtime.lastError while running tabs.captureVisibleTab: Failed to capture tab: unknown error
    at chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/src/js/pages/hensei-capture.js:104:19
    at chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/src/js/pages/hensei-capture.js:25:13
    at chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/src/js/pages/hensei-capture.js:20:18
    at Object.callback (chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/src/js/pages/hensei-capture.js:16:12)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
unsafe:data:,:1 GET unsafe:data:, net::ERR_UNKNOWN_URL_SCHEME
undefined:1 GET chrome-extension://iachoklpnnjfgmldgelflgifhdaebnol/src/html/undefined net::ERR_FILE_NOT_FOUND
```

<img width="809" alt="2015-09-11 8 58 35" src="https://cloud.githubusercontent.com/assets/1457682/9803979/77b7a47a-5863-11e5-9eb8-55bdd0623d82.png">

**Comment by otiai10** [comment]
@akiomik ありがとうございます。
経験則的には、ウィジェットの窓に一度フォーカス当てると治る感じなんですが、調査してみます。

---------------

@otiai10

- https://code.google.com/p/chromedriver/issues/detail?id=1083

**Comment by otiai10** [comment]
https://github.com/otiai10/kanColleWidget/blob/develop/src/js/pages/hensei-capture.js#L12-L31

tabs.queryのほうがいいかも

```js
chrome.tabs.query({url:['http://osapi.dmm.com/*']}, function(res) { console.log('res', res); });
```

**Comment by otiai10** [comment]
v2で作り直す
